### ISSUE TITLE
Do not get next challenge after given the right answer

### ISSUE THREAD

**Issue by oxmie** [social-dist0rtion-protocol/thc#8]
I got `thc`, `ethnode` and `ipfs` running, but if I gave the right answer, I always get the website message "Wrong solution :(" 

(I am using the test story `make backend` + `cd app; npm start`)

My software versions are:
```bash
# ipfs version
ipfs version 0.4.23
```
```bash
# npm version
{ npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.37.0',
  node: '11.15.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.27.0',
  v8: '7.0.276.38-node.19',
  zlib: '1.2.11' }
```
```bash
# ethnode --version
0.0.18
```

I think it has to be some problem within the Ethereum transactions, because if I look inside the `ethnode` logs I will get following answer (if I gave the right answer):
```bash
WARN [02-29|16:26:42.282] Served eth_sendRawTransaction            conn=127.0.0.1:56862 reqid=54 t=565.491µs   err="insufficient funds for gas * price + value"
```
When I put in a wrong answer for the challenge, I get following `ethnode` warning:
```bash
WARN [02-29|16:32:07.325] Served eth_estimateGas                   conn=127.0.0.1:56862 reqid=138 t=11.575711ms err="gas required exceeds allowance (8117970) or always failing transaction"

```

**Comment by vrde** [comment]
Hi, really sorry for this late reply. It might be because the player you are using has no ether in their wallet. 

Do you see a banner like this one?

![image](https://user-images.githubusercontent.com/134680/104810625-3eac9080-57f6-11eb-9410-3ca9fb19e686.png)

If you are still interested in trying out THC keep an eye on this repo, we are refactoring the code and make it easier to use.

**Comment by vrde** [comment]
Fixed! It took only 984 days.
